In [38]:
#Read the pima-indians-diabetes data file.
import numpy as np
import pandas as pd

from pandas import read_csv

dataset = read_csv('pima-indians-diabetes.data.csv',header=None)
dataset

0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
5     5  116  74   0    0  25.6  0.201  30  0
6     3   78  50  32   88  31.0  0.248  26  1
7    10  115   0   0    0  35.3  0.134  29  0
8     2  197  70  45  543  30.5  0.158  53  1
9     8  125  96   0    0   0.0  0.232  54  1
10    4  110  92   0    0  37.6  0.191  30  0
11   10  168  74   0    0  38.0  0.537  34  1
12   10  139  80   0    0  27.1  1.441  57  0
13    1  189  60  23  846  30.1  0.398  59  1
14    5  166  72  19  175  25.8  0.587  51  1
15    7  100   0   0    0  30.0  0.484  32  1
16    0  118  84  47  230  45.8  0.551  31  1
17    7  107  74   0    0  29.6  0.254  31  1
18    1  103  30  38   83  43.3  0.183  33  0
19    1  115  70  30   96  34.6  0.529  32  1
20    3  126  88  41  235  39.3  0.704  27  0
21    8   99  84   0    0  35.4  0.388  50  0
22    7  196  90   0    0  39.8  0.451  41  1
23    9  119  80  35    0  29.0  0.263  29  1
24   11  143  94  33  146  36.6  0.254  51  1
25   10  125  70  26  115  31.1  0.205  41  1
26    7  147  76   0    0  39.4  0.257  43  1
27    1   97  66  15  140  23.2  0.487  22  0
28   13  145  82  19  110  22.2  0.245  57  0
29    5  117  92   0    0  34.1  0.337  38  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
738   2   99  60  17  160  36.6  0.453  21  0
739   1  102  74   0    0  39.5  0.293  42  1
740  11  120  80  37  150  42.3  0.785  48  1
741   3  102  44  20   94  30.8  0.400  26  0
742   1  109  58  18  116  28.5  0.219  22  0
743   9  140  94   0    0  32.7  0.734  45  1
744  13  153  88  37  140  40.6  1.174  39  0
745  12  100  84  33  105  30.0  0.488  46  0
746   1  147  94  41    0  49.3  0.358  27  1
747   1   81  74  41   57  46.3  1.096  32  0
748   3  187  70  22  200  36.4  0.408  36  1
749   6  162  62   0    0  24.3  0.178  50  1
750   4  136  70   0    0  31.2  1.182  22  1
751   1  121  78  39   74  39.0  0.261  28  0
752   3  108  62  24    0  26.0  0.223  25  0
753   0  181  88  44  510  43.3  0.222  26  1
754   8  154  78  32    0  32.4  0.443  45  1
755   1  128  88  39  110  36.5  1.057  37  1
756   7  137  90  41    0  32.0  0.391  39  0
757   0  123  72   0    0  36.3  0.258  52  1
758   1  106  76   0    0  37.5  0.197  26  0
759   6  190  92   0    0  35.5  0.278  66  1
760   2   88  58  26   16  28.4  0.766  22  0
761   9  170  74  31    0  44.0  0.403  43  1
762   9   89  62   0    0  22.5  0.142  33  0
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

In [39]:
#Print the number of null values in the 7th column.
print(dataset.isnull().sum()[7])

dataset[7].isnull().sum()

0


0

In [40]:
#Print the count of total number of null values in the dataset.
print(dataset.isnull().sum().sum())

#Replacing 0 by NaN and then counting total number of null values
dataset = dataset.replace(0,np.NaN);
print(dataset)

dataset.isnull().sum().sum()

0
        0      1     2     3      4     5      6   7    8
0     6.0  148.0  72.0  35.0    NaN  33.6  0.627  50  1.0
1     1.0   85.0  66.0  29.0    NaN  26.6  0.351  31  NaN
2     8.0  183.0  64.0   NaN    NaN  23.3  0.672  32  1.0
3     1.0   89.0  66.0  23.0   94.0  28.1  0.167  21  NaN
4     NaN  137.0  40.0  35.0  168.0  43.1  2.288  33  1.0
5     5.0  116.0  74.0   NaN    NaN  25.6  0.201  30  NaN
6     3.0   78.0  50.0  32.0   88.0  31.0  0.248  26  1.0
7    10.0  115.0   NaN   NaN    NaN  35.3  0.134  29  NaN
8     2.0  197.0  70.0  45.0  543.0  30.5  0.158  53  1.0
9     8.0  125.0  96.0   NaN    NaN   NaN  0.232  54  1.0
10    4.0  110.0  92.0   NaN    NaN  37.6  0.191  30  NaN
11   10.0  168.0  74.0   NaN    NaN  38.0  0.537  34  1.0
12   10.0  139.0  80.0   NaN    NaN  27.1  1.441  57  NaN
13    1.0  189.0  60.0  23.0  846.0  30.1  0.398  59  1.0
14    5.0  166.0  72.0  19.0  175.0  25.8  0.587  51  1.0
15    7.0  100.0   NaN   NaN    NaN  30.0  0.484  32  1.0
16    NaN  1

1263

In [22]:
#Replace the missing values with the median of the respective columns.
dataset.fillna(dataset.mean(),inplace=True)

print(dataset.isnull().sum())

dataset

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64


0      1          2         3           4          5      6   7  \
0     6.000000  148.0  72.000000  35.00000  155.548223  33.600000  0.627  50   
1     1.000000   85.0  66.000000  29.00000  155.548223  26.600000  0.351  31   
2     8.000000  183.0  64.000000  29.15342  155.548223  23.300000  0.672  32   
3     1.000000   89.0  66.000000  23.00000   94.000000  28.100000  0.167  21   
4     4.494673  137.0  40.000000  35.00000  168.000000  43.100000  2.288  33   
5     5.000000  116.0  74.000000  29.15342  155.548223  25.600000  0.201  30   
6     3.000000   78.0  50.000000  32.00000   88.000000  31.000000  0.248  26   
7    10.000000  115.0  72.405184  29.15342  155.548223  35.300000  0.134  29   
8     2.000000  197.0  70.000000  45.00000  543.000000  30.500000  0.158  53   
9     8.000000  125.0  96.000000  29.15342  155.548223  32.457464  0.232  54   
10    4.000000  110.0  92.000000  29.15342  155.548223  37.600000  0.191  30   
11   10.000000  168.0  74.000000  29.15342  155.548223  38.000000  0.537  34   
12   10.000000  139.0  80.000000  29.15342  155.548223  27.100000  1.441  57   
13    1.000000  189.0  60.000000  23.00000  846.000000  30.100000  0.398  59   
14    5.000000  166.0  72.000000  19.00000  175.000000  25.800000  0.587  51   
15    7.000000  100.0  72.405184  29.15342  155.548223  30.000000  0.484  32   
16    4.494673  118.0  84.000000  47.00000  230.000000  45.800000  0.551  31   
17    7.000000  107.0  74.000000  29.15342  155.548223  29.600000  0.254  31   
18    1.000000  103.0  30.000000  38.00000   83.000000  43.300000  0.183  33   
19    1.000000  115.0  70.000000  30.00000   96.000000  34.600000  0.529  32   
20    3.000000  126.0  88.000000  41.00000  235.000000  39.300000  0.704  27   
21    8.000000   99.0  84.000000  29.15342  155.548223  35.400000  0.388  50   
22    7.000000  196.0  90.000000  29.15342  155.548223  39.800000  0.451  41   
23    9.000000  119.0  80.000000  35.00000  155.548223  29.000000  0.263  29   
24   11.000000  143.0  94.000000  33.00000  146.000000  36.600000  0.254  51   
25   10.000000  125.0  70.000000  26.00000  115.000000  31.100000  0.205  41   
26    7.000000  147.0  76.000000  29.15342  155.548223  39.400000  0.257  43   
27    1.000000   97.0  66.000000  15.00000  140.000000  23.200000  0.487  22   
28   13.000000  145.0  82.000000  19.00000  110.000000  22.200000  0.245  57   
29    5.000000  117.0  92.000000  29.15342  155.548223  34.100000  0.337  38   
..         ...    ...        ...       ...         ...        ...    ...  ..   
738   2.000000   99.0  60.000000  17.00000  160.000000  36.600000  0.453  21   
739   1.000000  102.0  74.000000  29.15342  155.548223  39.500000  0.293  42   
740  11.000000  120.0  80.000000  37.00000  150.000000  42.300000  0.785  48   
741   3.000000  102.0  44.000000  20.00000   94.000000  30.800000  0.400  26   
742   1.000000  109.0  58.000000  18.00000  116.000000  28.500000  0.219  22   
743   9.000000  140.0  94.000000  29.15342  155.548223  32.700000  0.734  45   
744  13.000000  153.0  88.000000  37.00000  140.000000  40.600000  1.174  39   
745  12.000000  100.0  84.000000  33.00000  105.000000  30.000000  0.488  46   
746   1.000000  147.0  94.000000  41.00000  155.548223  49.300000  0.358  27   
747   1.000000   81.0  74.000000  41.00000   57.000000  46.300000  1.096  32   
748   3.000000  187.0  70.000000  22.00000  200.000000  36.400000  0.408  36   
749   6.000000  162.0  62.000000  29.15342  155.548223  24.300000  0.178  50   
750   4.000000  136.0  70.000000  29.15342  155.548223  31.200000  1.182  22   
751   1.000000  121.0  78.000000  39.00000   74.000000  39.000000  0.261  28   
752   3.000000  108.0  62.000000  24.00000  155.548223  26.000000  0.223  25   
753   4.494673  181.0  88.000000  44.00000  510.000000  43.300000  0.222  26   
754   8.000000  154.0  78.000000  32.00000  155.548223  32.400000  0.443  45   
755   1.000000  128.0  88.000000  39.00000  110.000000  36.500000  1.057  37   
756   7.00000

In [23]:
#Print the count of total number of rows having missing values.
print(sum([True for idx,row in dataset.iterrows() if any (row.isnull())]))

0


In [28]:
#Print the count of number of cells in the rows 120 to 198.
dataset[120:199].shape[0]*dataset[120:199].shape[1]

711

In [14]:
#Create any dataframe and sample out 30% values from the dataframe.
df = pd.DataFrame({'Hello':[1,2,3,4], 'World':[5,6,7,8]}, index=['Any','Random','Value','Here'])
print(df)

df.sample(frac=0.3,replace=True,random_state=None)

        Hello  World
Any         1      5
Random      2      6
Value       3      7
Here        4      8


Hello  World
Any      1      5

In [32]:
#Create a dataframe having 4 columns and 4 rows and having random values.Normalize it using min max normalisation.
df2 = pd.DataFrame(np.random.rand(4,4),columns=list('ABCD'),index=list('1234'))
print(df2)

normalized_df = (df2-df2.min())/(df2.max()-df2.min())
print(normalized_df)

          A         B         C         D
1  0.706018  0.399190  0.751652  0.880838
2  0.193489  0.483483  0.612829  0.222767
3  0.762998  0.634842  0.141009  0.574347
4  0.789383  0.864801  0.196040  0.713134
          A         B         C         D
1  0.860101  0.000000  1.000000  1.000000
2  0.000000  0.181038  0.772661  0.000000
3  0.955723  0.506114  0.000000  0.534258
4  1.000000  1.000000  0.090119  0.745157


In [34]:
#Create a 2d numpy array of size (4,4)having 1 in first row ,2 in second row and so on.Find the correlation coefficient.
arr = np.random.rand(4,4)
arr[0]=1
arr[1]=2
arr[2]=3
arr[3]=4
print(arr)

np.corrcoef(arr,y=None,rowvar=True)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


C:\Users\FDUSER.M-1734.002\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2400: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]


array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [44]:
#Create a numpy array having values 4,2,7,23,6.Print the interval corresponding to each value where first interval is 0 to 2
#,second interval is 2 to 4 and so on. 
arr2 = np.array([4,2,7,23,6])
print(arr2)
bins = np.array([i for i in range(0,25,2)])
print(bins)
inds = np.digitize(arr2,bins,right=False)
inds

[ 4  2  7 23  6]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24]


array([ 3,  2,  4, 12,  4], dtype=int64)

In [41]:
#Replace missing values in the dataset with inf value.
dataset.fillna(np.inf,inplace=True)
dataset

0      1          2          3           4          5      6   7  \
0     6.000000  148.0  72.000000  35.000000         inf  33.600000  0.627  50   
1     1.000000   85.0  66.000000  29.000000         inf  26.600000  0.351  31   
2     8.000000  183.0  64.000000        inf         inf  23.300000  0.672  32   
3     1.000000   89.0  66.000000  23.000000   94.000000  28.100000  0.167  21   
4          inf  137.0  40.000000  35.000000  168.000000  43.100000  2.288  33   
5     5.000000  116.0  74.000000        inf         inf  25.600000  0.201  30   
6     3.000000   78.0  50.000000  32.000000   88.000000  31.000000  0.248  26   
7    10.000000  115.0        inf        inf         inf  35.300000  0.134  29   
8     2.000000  197.0  70.000000  45.000000  543.000000  30.500000  0.158  53   
9     8.000000  125.0  96.000000        inf         inf        inf  0.232  54   
10    4.000000  110.0  92.000000        inf         inf  37.600000  0.191  30   
11   10.000000  168.0  74.000000        inf         inf  38.000000  0.537  34   
12   10.000000  139.0  80.000000        inf         inf  27.100000  1.441  57   
13    1.000000  189.0  60.000000  23.000000  846.000000  30.100000  0.398  59   
14    5.000000  166.0  72.000000  19.000000  175.000000  25.800000  0.587  51   
15    7.000000  100.0        inf        inf         inf  30.000000  0.484  32   
16         inf  118.0  84.000000  47.000000  230.000000  45.800000  0.551  31   
17    7.000000  107.0  74.000000        inf         inf  29.600000  0.254  31   
18    1.000000  103.0  30.000000  38.000000   83.000000  43.300000  0.183  33   
19    1.000000  115.0  70.000000  30.000000   96.000000  34.600000  0.529  32   
20    3.000000  126.0  88.000000  41.000000  235.000000  39.300000  0.704  27   
21    8.000000   99.0  84.000000        inf         inf  35.400000  0.388  50   
22    7.000000  196.0  90.000000        inf         inf  39.800000  0.451  41   
23    9.000000  119.0  80.000000  35.000000         inf  29.000000  0.263  29   
24   11.000000  143.0  94.000000  33.000000  146.000000  36.600000  0.254  51   
25   10.000000  125.0  70.000000  26.000000  115.000000  31.100000  0.205  41   
26    7.000000  147.0  76.000000        inf         inf  39.400000  0.257  43   
27    1.000000   97.0  66.000000  15.000000  140.000000  23.200000  0.487  22   
28   13.000000  145.0  82.000000  19.000000  110.000000  22.200000  0.245  57   
29    5.000000  117.0  92.000000        inf         inf  34.100000  0.337  38   
..         ...    ...        ...        ...         ...        ...    ...  ..   
738   2.000000   99.0  60.000000  17.000000  160.000000  36.600000  0.453  21   
739   1.000000  102.0  74.000000        inf         inf  39.500000  0.293  42   
740  11.000000  120.0  80.000000  37.000000  150.000000  42.300000  0.785  48   
741   3.000000  102.0  44.000000  20.000000   94.000000  30.800000  0.400  26   
742   1.000000  109.0  58.000000  18.000000  116.000000  28.500000  0.219  22   
743   9.000000  140.0  94.000000        inf         inf  32.700000  0.734  45   
744  13.000000  153.0  88.000000  37.000000  140.000000  40.600000  1.174  39   
745  12.000000  100.0  84.000000  33.000000  105.000000  30.000000  0.488  46   
746   1.000000  147.0  94.000000  41.000000         inf  49.300000  0.358  27   
747   1.000000   81.0  74.000000  41.000000   57.000000  46.300000  1.096  32   
748   3.000000  187.0  70.000000  22.000000  200.000000  36.400000  0.408  36   
749   6.000000  162.0  62.000000        inf         inf  24.300000  0.178  50   
750   4.000000  136.0  70.000000        inf         inf  31.200000  1.182  22   
751   1.000000  121.0  78.000000  39.000000   74.000000  39.000000  0.261  28   
752   3.000000  108.0  62.000000  24.000000         inf  26.000000  0.223  25   
753        inf  181.0  88.000000  44.000000  510.000000  43.300000  0.222  26   
754   8.000000  154.0  78.000000  32.000000         inf  32.400000  0.443  45   
755   1.000000  128.0  88.000000  39.000000 