# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [4]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2) 
#first argument = starting point
# second argument = ending point excluding it
# third argument = difference

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,50,False,True)

(array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
        2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
        5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
        7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]), 0.2)

## eye

Creates an identity matrix

In [16]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [17]:
np.random.rand(2)

array([0.74744196, 0.33422916])

In [18]:
np.random.rand(5,5)
#dimensions are not passed as tuple unlike in np.zeros()

array([[0.83891026, 0.15321256, 0.4811082 , 0.28788036, 0.37142777],
       [0.50617576, 0.53487635, 0.14110786, 0.10319818, 0.33008613],
       [0.54770458, 0.90983104, 0.83536019, 0.90399712, 0.29233269],
       [0.39013752, 0.35382626, 0.54356558, 0.0060506 , 0.11527243],
       [0.01064354, 0.98727673, 0.18582963, 0.14479493, 0.49309944]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [19]:
np.random.randn(2)

array([-0.13494734, -1.14413058])

In [20]:
np.random.randn(5,5)

array([[-0.23925044,  1.06735266,  0.9365924 ,  1.98750188, -1.12675373],
       [-0.46869423, -2.23263934, -0.81358868, -1.8664089 , -0.24829687],
       [-0.15782949, -1.25239125,  0.82966158, -1.89767855,  1.67214679],
       [ 1.13613618,  0.00982702, -1.01735547,  1.9409979 , -0.26166687],
       [ 0.10543563, -0.21522679, -0.47189356,  1.19787069, -0.07627161]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [21]:
np.random.randint(1,100)

31

## Reshape
Returns an array containing the same data with a new shape.

In [31]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [27]:
arr = np.array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39]) 

In [28]:
print(arr.max())
print(arr.argmax())
print(arr.min())
print(arr.argmin())

49
4
2
5


## Shape

Shape is an attribute that arrays have (not a method):

In [29]:
# Vector
arr.shape

(10,)

In [33]:
# Notice the two sets of brackets
arr.reshape(25,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

In [34]:
arr.reshape(1,25).shape

(1, 25)

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [35]:
arr = np.arange(0,10)

In [41]:
arr + arr # change + with any operation

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [40]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [42]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [43]:
np.log(arr)

C:\Users\FDUSER.M-1934.004\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# Great Job!