In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

## Get the Data

In [2]:
data = pd.read_csv('spambase_data.csv',header=None)
data.head()

0     1     2    3     4     5     6     7     8     9  ...    48     49  \
0  0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00 ...  0.00  0.000   
1  0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94 ...  0.00  0.132   
2  0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25 ...  0.01  0.143   
3  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63 ...  0.00  0.137   
4  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63 ...  0.00  0.135   

    50     51     52     53     54   55    56  57  
0  0.0  0.778  0.000  0.000  3.756   61   278   1  
1  0.0  0.372  0.180  0.048  5.114  101  1028   1  
2  0.0  0.276  0.184  0.010  9.821  485  2259   1  
3  0.0  0.137  0.000  0.000  3.537   40   191   1  
4  0.0  0.135  0.000  0.000  3.537   40   191   1  

[5 rows x 58 columns]

In [3]:
X = data.drop(57,axis=1)
y = data[57]

## Train, Test Split

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=101)

## Random Forests

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(X_train,y_train)

In [8]:
predictions = clf.predict(X_test)

In [9]:
print(confusion_matrix(y_test,predictions))
print()
print(classification_report(y_test,predictions))

[[542  19]
 [ 41 319]]

              precision    recall  f1-score   support

           0       0.93      0.97      0.95       561
           1       0.94      0.89      0.91       360

   micro avg       0.93      0.93      0.93       921
   macro avg       0.94      0.93      0.93       921
weighted avg       0.94      0.93      0.93       921



## Bagging 

In [10]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier

In [11]:
bagging = BaggingClassifier(KNeighborsClassifier(),max_samples=0.5, max_features=0.5)
bagging = bagging.fit(X_train,y_train)

In [12]:
predictions = bagging.predict(X_test)

In [13]:
print(confusion_matrix(y_test,predictions))
print()
print(classification_report(y_test,predictions))

[[502  59]
 [ 94 266]]

              precision    recall  f1-score   support

           0       0.84      0.89      0.87       561
           1       0.82      0.74      0.78       360

   micro avg       0.83      0.83      0.83       921
   macro avg       0.83      0.82      0.82       921
weighted avg       0.83      0.83      0.83       921



## AdaBoost

In [14]:
from sklearn.ensemble import AdaBoostClassifier

In [15]:
boost = AdaBoostClassifier(n_estimators=10)
boost = boost.fit(X_train,y_train)

In [16]:
predictions = boost.predict(X_test)

In [17]:
print(confusion_matrix(y_test,predictions))
print()
print(classification_report(y_test,predictions))

[[539  22]
 [ 56 304]]

              precision    recall  f1-score   support

           0       0.91      0.96      0.93       561
           1       0.93      0.84      0.89       360

   micro avg       0.92      0.92      0.92       921
   macro avg       0.92      0.90      0.91       921
weighted avg       0.92      0.92      0.91       921

